num1 = input("Enter a number: ")
num1 = int(num1)
num2 = input("Enter second number: ")
num2 = int(num2)
num3 = input("Enter third number: ")
num3 = int(num3)
print("The difference is: ", num1-num2-num3)