num1 = input("Enter the first number: ")
num1 = int(num1)
num2 = input("Enter the second number: ")
num2 = int(num2)
num3 = input("Enter the third number: ")
num3 = int(num3)
print("The sum is: ", num1+num2-num3)